# Generated by Django 6.0.7 on 2026-08-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_system', '0001_initial'),
        ('cars', '0001_initial'),
        ('drivers', '0010_driver_pan_card_driver_police_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.customercar'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.driver'),
        ),
    ]
