# Generated by Django 6.0.7 on 2026-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_created_at_driver_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
