# Generated by Django 6.0.7 on 2026-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
