# Generated by Django 6.0.7 on 2026-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
