# Generated by Django 6.0.7 on 2026-07-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
