# Generated by Django 6.0.7 on 2026-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_driver_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
