# Generated by Django 6.0.7 on 2026-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driver_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driving_licence',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/licence/'),
        ),
    ]
