# Generated by Django 6.0.7 on 2026-07-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_driver_driving_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aadhaar_back',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/aadhaar/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='aadhaar_front',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/aadhaar/'),
        ),
    ]
