# Generated by Django 6.0.7 on 2026-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_driver_aadhaar_back_driver_aadhaar_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/pan/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='police_verification',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/police_verification/'),
        ),
    ]
